# Generated by Django 5.1.7 on 2025-03-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('warehouse manager', 'Warehouse Manager'), ('restaurant manager', 'Restaurant Manager')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse_inventory.user')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('bank_acc_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse_inventory.user')),
            ],
        ),
        migrations.CreateModel(
            name='RequestToJoin',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.restaurantmanager')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.restaurantmanager'),
        ),
    ]
