# Generated by Django 5.1.7 on 2025-03-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.restaurantmanager'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.order'),
        ),
        migrations.AlterField(
            model_name='requesttojoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.restaurantmanager'),
        ),
        migrations.AlterField(
            model_name='restaurantmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse_inventory.user'),
        ),
        migrations.AlterField(
            model_name='warehousemanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse_inventory.user'),
        ),
    ]
